server.port: 8081

spring:
  application:
    name: beverages-ms
  datasource:
    url: jdbc:mysql://localhost:3306/beverages?useSSL=false&user=root&password=password

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

