server.port: 8082

spring:
  application:
    name: appetizers-ms
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/appetizers?useSSL=false&user=root&password=password